version: "3.9"
services:
  oracle:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "system"
    volumes:
      - ./init_oracle:/container-entrypoint-initdb.d

  app:
    build:
      context: .
    ports:
      - "1323:1323"
        #restart: always
    environment:
      USER: test
      PASS: test
      HOST: oracle
      PORT: 1501
      SERVICE: XEPDB1

    volumes:
      - ./data:/data
    depends_on:
      - oracle

